### ISSUE TITLE
Feature request: multi-blur

### ISSUE THREAD

**Issue by lebe-dev** [kakoc/birdy#1]
It would be great to have blur feature to mask sensitive content. 

Also I would suggest to do multi-blur effect, not just once.
Security experts introduced method how to recover text after blur.

Usually I do multiple blur over sensitive information, but I do it manually.

Thank you for your project :)

**Comment by kakoc** [comment]
I'm not sure how to pickup a solution which is proven to be safe. I will play with that.  
For now you can use a filled rectangle which is 100% safe to use since it totally overrides pixels under it.  

It looks like this:
![image](https://github.com/kakoc/birdy/assets/16936618/a935a06e-dda2-4960-a4e5-21acb248d1ca)

**Comment by lebe-dev** [comment]
Thanks for suggestion.

Solution for secure blur: apply to selected area blur multiple times in random coordinates :)

**Comment by stefnotch** [comment]
A secure and decent option would be
1. Get the average color of a region
2. Replace the region with the average color
3. Blur it, so that there's no noticeable border

**Comment by kakoc** [comment]
Added the initial version.  
![image](https://github.com/kakoc/birdy/assets/16936618/c2787d47-e275-48a0-9394-d1f0392b290e)
